version: "3"
services: 
  frontend:
    build:
      dockerfile: Dockerfile.dev
      context: ./my-blog
    container_name: my-blog
    #코드 수정후 다시이미지 build없이 코드가 반영 될 수 있게 volume을 사용한다.
    volumes:
      - ./my-blog:/app
      - /app/node_modules     
    stdin_open: true
    shm_size: '5gb'

  nginx:
    #재시작 정책
    #no: 어떠한 상황에서도 재시작을 하지 않습니다
    #always: 항상 재시작
    #on-failure: 에러코드와 함께 컨테이너가 멈추었을 때만 재시작 
    #unless-stopped 개발자가 임의로 멈추려고 할때 빼고는 항상 재시작
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "80:80"  

  backend:
    build: 
      dockerfile: Dockerfile.dev
      context: ./my-blog-server
    container_name: my-blog-server
    volumes:
      - ./my-blog-server:/app
      - /app/node_modules      
    shm_size: '5gb'  

  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_DATABASE: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
    volumes:
      - ./mysql/my.cnf:/etc/mysql/my.cnf
      - ./mysql/data:/var/lib/mysql
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    shm_size: '5gb'
    #mysql의 root 비밀번호와 db를 설정해준다.
    