version: "3"
services: 
  mysql:
    build:
        dockerfile: Dockerfile
        context: ./mysql
    restart: always
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    volumes:
      - "~/mysql/data:/var/lib/mysql"
    ports:
      - "3306:3306"
    shm_size: '5gb'
    #mysql의 root 비밀번호와 db를 설정해준다.
    
  frontend:
    image : ks78mk2/my-blog
    container_name: frontend
    #코드 수정후 다시 이미지 build없이 코드가 반영 될 수 있게 volume을 사용한다.
    stdin_open: true
    shm_size: '5gb'
    
  nginx:
    #재시작 정책
    #no: 어떠한 상황에서도 재시작을 하지 않습니다
    #always: 항상 재시작
    #on-failure: 에러코드와 함께 컨테이너가 멈추었을 때만 재시작 
    #unless-stopped 개발자가 임의로 멈추려고 할때 빼고는 항상 재시작
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "80:80"

  backend:
    image: ks78mk2/my-blog-server
    container_name: backend
    volumes:
      - ./my-blog-server:/app
      - /app/node_modules
      - /home/opc/my-blog-server-static/node_modules:/app/node_modules      
    shm_size: '5gb'  
  